services:
  sub:
    build:
      context: .
    image: sub:0.1.19
    container_name: sub
    restart: unless-stopped
    networks:
      - ext
    ports:
      - "50014:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apex.rule=Host(`sub.si`)"
      - "traefik.http.routers.apex.entrypoints=websecure"
      - "traefik.http.routers.apex.tls.certresolver=apex"
      - "traefik.http.services.apex.loadbalancer.server.port=80"

networks:
  ext:
    external: true
