services:
  sub:
    build:
      context: .
    image: sub:0.1.17
    container_name: sub
    restart: unless-stopped
    networks:
      - ext
    ports:
      - "5080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.root.rule=Host(`sub.si`)"
      - "traefik.http.routers.root.entrypoints=websecure"
      - "traefik.http.routers.root.tls.certresolver=root"
      - "traefik.http.services.root.loadbalancer.server.port=80"

networks:
  ext:
    external: true
