services:
  sub:
    build:
      context: "."
      dockerfile: "Containerfile"
    image: "sub:0.1.21"
    container_name: "sub"
    restart: "unless-stopped"
    networks:
      - "ext"
    ports:
      - "50014:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apex.rule=Host(`sub.si`)"
      - "traefik.http.routers.apex.entrypoints=websecure"
      - "traefik.http.routers.apex.tls.certresolver=cloudflare"
      - "traefik.http.routers.apex.tls.domains[0].main=sub.si"
      - "traefik.http.routers.apex.tls.domains[0].sans=*.sub.si"
      - "traefik.http.services.apex.loadbalancer.server.port=80"

networks:
  ext:
    external: true
